apimServiceName: nitz-apim-prd
namedValues:
  - name: samplesecret
    properties:
      displayName: samplesecret
      value: "prodsecret"
  - name: nitzpythonfunctionapp-key
    properties:
      displayName: nitzpythonfunctionapp-key
      value: "oqte3oAGCtBjk5upDur2pNv6UugcuCusZHX97zk1TBawAzFuZ5g4dA=="
  - name: kv-secret
    properties:
      displayName: kv-secret
      keyVault:
        identityClientId: d9e8b972-2987-4fe5-b346-63e5425bc87d
        secretIdentifier: https://nitz-key-vault.vault.azure.net/secrets/api-key-prod/a32022bc682642339b4483c0a9321579
loggers:
    - name: nitz-appinsights-test
      properties:
        loggerType: applicationInsights
        description: Prod Application Insights
        resourceId: "/subscriptions/873df924-afb6-443d-9e82-2be75cd78756/resourceGroups/target-nitz-rg/providers/microsoft.insights/components/nitz-appinsights-test"
        credentials:
          instrumentationKey: "c886d3b6-8f5b-4e94-9653-74f8c1ec4c3d"
        isBuffered: true
diagnostics:
backends:
  - name: nitzpythonfunctionapp
    properties:
      url: "https://nitzpythonfunctionapp-prod.azurewebsites.net/api"
      resourceid: "https://management.azure.com/subscriptions/873df924-afb6-443d-9e82-2be75cd78756/resourceGroups/nitzpythonfunctionapp_group/providers/Microsoft.Web/sites/nitzpythonfunctionapp-prod"
apis:
  - name: demo-conference-api
    diagnostics:
      - name: applicationinsights
        properties:
          verbosity: Error
          loggerId: "/subscriptions/873df924-afb6-443d-9e82-2be75cd78756/resourceGroups/target-nitz-rg/providers/Microsoft.ApiManagement/service/nitz-apim-prd/loggers/nitz-appinsights-prd"

